-- SHOULD BE IN THE DATABASE THAT CONTAINS THE SCHEMA;
-- GENERIC SINTAX:
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA <schema_name> to <user_name>;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public to CSharpAccess;